import { ThemeProvider } from "@/components/ThemeProvider/theme-provier";
import { Toaster } from "@/components/ui/sonner";
import { createClient } from "@/lib/supabase/server";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { UserProvider } from "@/providers/UserProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased font-sans`}
        suppressHydrationWarning
      >
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <UserProvider initialUser={data?.user}>
              <main className="bg-[#ebebeb] dark:bg-card min-h-screen">
                <Toaster />
                {children}
              </main>
            </UserProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
