export const CATEGORIES = [
  "Activités maritimes",
  "Agriculture / Agroalimentaire",
  "Alimentation & Boissons",
  "Animaux domestiques",
  "Application / Site Web",
  "Art",
  "Artisanat",
  "Articles Ménagers / Design d'Intérieur",
  "Automobile / Transport",
  "Beauté",
  "Bricolage / Bâtiment",
  "Construction",
  "Divertissement / Expérience",
  "Écologie / Environnement",
  "Éducation",
  "Enfants",
  "Événementiel / Organisation d'événements",
  "Fêtes",
  "Finance / Investissement",
  "Fitness",
  "Immobilier",
  "Industries créatives",
  "Jouets / Jeux",
  "Médias / Communication",
  "Mode de vie durable",
  "Musique",
  "Pêche",
  "Restauration / Hôtellerie",
  "Santé / Bien-être / Nutrition",
  "Services de santé",
  "Services en ligne",
  "Services professionnels",
  "Services sociaux / Communautaires",
  "Sports",
  "Technologie",
  "Technologie de pointe",
  "Télécommunications",
  "Vêtements / Mode",
  "Voyage / Tourisme",
];

export const CATEGORY_OPTIONS = CATEGORIES.map((category) => ({
  value: category,
  label: category,
}));
